name: sysmicro
dependencies:
- biopython
- bokeh
- jupyter
- matplotlib
- pandas
- python
- scikit-learn
- scipy
- seaborn
- pip:
  - joblib==0.9.3
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
