name: sysmicro
dependencies:
- appnope=0.1.0=py35_0
- biopython=1.66=np110py35_0
- bokeh=0.10.0=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.4=py35_0
- flask=0.10.1=py35_1
- freetype=2.5.5=0
- ipykernel=4.1.1=py35_0
- ipython=4.0.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.0=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.0.3=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.0=np110py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.0.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.0.6=py35_0
- numpy=1.10.1=py35_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_0
- python=3.5.0=1
- python-dateutil=2.4.2=py35_0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- pyzmq=14.7.0=py35_1
- qt=4.8.7=1
- qtconsole=4.1.0=py35_0
- readline=6.2=2
- requests=2.8.1=py35_0
- scikit-learn=0.17=np110py35_1
- scipy=0.16.0=np110py35_1
- seaborn=0.6.0=np110py35_0
- setuptools=18.5=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.8.4.1=1
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- werkzeug=0.11.2=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - joblib==0.9.3
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
